name: 🎯 Add New Activity
description: Request to add a new extracurricular activity to the system
title: "Add New Activity: [Activity Name]"
labels: ["enhancement", "new-activity", "teacher-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for requesting a new activity! Please provide the details below so our development team can add it to the system.
        
  - type: input
    id: activity-name
    attributes:
      label: Activity Name
      description: What is the name of the new activity?
      placeholder: e.g., "Photography Club", "Student Council", "Volunteer Club"
    validations:
      required: true

  - type: textarea
    id: activity-description
    attributes:
      label: Activity Description
      description: Provide a detailed description of what this activity involves
      placeholder: "Describe what students will do in this activity, skills they'll learn, etc."
    validations:
      required: true

  - type: dropdown
    id: activity-category
    attributes:
      label: Activity Category
      description: What type of activity is this?
      options:
        - Academic (Math, Science, etc.)
        - Arts & Creative (Drama, Art, Music)
        - Sports & Fitness
        - Technology (Robotics, Coding)
        - Community Service
        - Special Interest (Chess, Gaming)
        - Leadership & Governance
        - Other
    validations:
      required: true

  - type: input
    id: teacher-sponsor
    attributes:
      label: Teacher Sponsor Username
      description: Which teacher will sponsor this activity? (use their login username)
      placeholder: e.g., "mrodriguez", "mchen"
    validations:
      required: true

  - type: checkboxes
    id: schedule-days
    attributes:
      label: Meeting Days
      description: Which days will this activity meet?
      options:
        - label: Monday
        - label: Tuesday
        - label: Wednesday
        - label: Thursday
        - label: Friday
        - label: Saturday
        - label: Sunday

  - type: input
    id: start-time
    attributes:
      label: Start Time
      description: What time does the activity start?
      placeholder: "e.g., 3:30 PM, 7:00 AM"
    validations:
      required: true

  - type: input
    id: end-time
    attributes:
      label: End Time
      description: What time does the activity end?
      placeholder: "e.g., 5:00 PM, 8:00 AM"
    validations:
      required: true

  - type: input
    id: max-participants
    attributes:
      label: Maximum Participants
      description: How many students can participate in this activity?
      placeholder: "e.g., 15, 20, 30"
    validations:
      required: true

  - type: textarea
    id: special-requirements
    attributes:
      label: Special Requirements or Notes
      description: Any special equipment, room requirements, or other important details?
      placeholder: "e.g., Requires art supplies, Computer lab needed, Outdoor space required"

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Check all that apply for this request to be considered complete
      options:
        - label: Activity appears in the activities list on the website
        - label: Teachers can register students for this activity
        - label: Activity shows correct schedule information
        - label: Activity displays proper capacity limits
        - label: Activity is categorized correctly with appropriate visual tags

  - type: markdown
    attributes:
      value: |
        ## For Development Team
        
        **Technical Implementation Notes:**
        - Add new activity entry to `src/backend/database.py` in the `initial_activities` dictionary
        - Ensure schedule_details format matches existing activities (24-hour time format)
        - Activity will be automatically categorized by frontend based on name/description keywords
        - Test teacher authentication and student registration functionality
        
        **Files to modify:**
        - `src/backend/database.py` - Add activity data
        - Potentially `src/static/app.js` - If new activity type categorization needed