blank_issues_enabled: false
contact_links:
  - name: 📚 Development Documentation
    url: https://github.com/dhopper506/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Learn about the technical details and development setup
  - name: 💬 General Questions
    url: https://github.com/dhopper506/skills-expand-your-team-with-copilot/discussions
    about: Ask questions or discuss ideas that don't fit the templates above